// Generated from the live Napoli7 POS catalog.
// Keep this file in sync if the POS team changes SKUs or prices.

export interface PosSkuEntry {
  name: string;
  size: "regular" | "small";
  price: number;
  sku: string;
  posName: string;
  posPrice: number;
}

export const POS_SKU_ENTRIES: readonly PosSkuEntry[] = [
  {
    name: "Indian - Spicy Chicken Kebab",
    size: "regular",
    price: 43,
    sku: "IND-0012",
    posName: "Indian - Spicy Chicken Kebab",
    posPrice: 43,
  },
  {
    name: "Indian - Spicy Chicken Kebab",
    size: "small",
    price: 29,
    sku: "SMA-0046",
    posName: "Small Spicy Chicken Kebab",
    posPrice: 29,
  },
  {
    name: "Indian - Paneer",
    size: "regular",
    price: 38,
    sku: "IND-0013",
    posName: "Indian - Paneer",
    posPrice: 38,
  },
  {
    name: "Indian - Paneer",
    size: "small",
    price: 25,
    sku: "SMA-0047",
    posName: "Small Paneer",
    posPrice: 25,
  },
  {
    name: "Indian - Vegan Tofu",
    size: "regular",
    price: 45,
    sku: "IND-0011",
    posName: "Indian - Vegan Tofu",
    posPrice: 45,
  },
  {
    name: "Indian - Vegan Tofu",
    size: "small",
    price: 31,
    sku: "SMA-0045",
    posName: "Small Indian - Vegan Tofu",
    posPrice: 32,
  },
  {
    name: "Pakistan - Mutton Kebab",
    size: "regular",
    price: 45,
    sku: "PAK-0014",
    posName: "Pakistan - Mutton Kebab",
    posPrice: 45,
  },
  {
    name: "Pakistan - Mutton Kebab",
    size: "small",
    price: 32,
    sku: "SMA-0048",
    posName: "Small Mutton Kebab",
    posPrice: 32,
  },
  {
    name: "UAE - Camel Kebab",
    size: "regular",
    price: 43,
    sku: "UAE-0015",
    posName: "UAE - Camel Kebab",
    posPrice: 43,
  },
  {
    name: "UAE - Camel Kebab",
    size: "small",
    price: 29,
    sku: "SMA-0049",
    posName: "Small Camel Kebab",
    posPrice: 29,
  },
  {
    name: "Bangladesh - Spicy Beef Kebab",
    size: "regular",
    price: 43,
    sku: "BAN-0016",
    posName: "Bangladesh - Spicy Beef Kebab",
    posPrice: 43,
  },
  {
    name: "Bangladesh - Spicy Beef Kebab",
    size: "small",
    price: 28,
    sku: "SMA-0050",
    posName: "Small Spicy Beef Kebab",
    posPrice: 29,
  },
  {
    name: "Afghanistan - Chicken Kebab",
    size: "regular",
    price: 43,
    sku: "AFG-0017",
    posName: "Afghanistan - Chicken Kebab",
    posPrice: 43,
  },
  {
    name: "Afghanistan - Chicken Kebab",
    size: "small",
    price: 29,
    sku: "SMA-0051",
    posName: "Small Chicken Kebab",
    posPrice: 29,
  },
  {
    name: "Filipino - Chicken Adobo",
    size: "regular",
    price: 39,
    sku: "FIL-0018",
    posName: "Filipino - Chicken Adobo",
    posPrice: 39,
  },
  {
    name: "Filipino - Chicken Adobo",
    size: "small",
    price: 25,
    sku: "SMA-0052",
    posName: "Small Chicken Adobo",
    posPrice: 25,
  },
  {
    name: "Egyptian - Merguez (Egyptian Sausage)",
    size: "regular",
    price: 36,
    sku: "EGY-0019",
    posName: "Egyptian - Merguez (Egyptian Sausage)",
    posPrice: 36,
  },
  {
    name: "Egyptian - Merguez (Egyptian Sausage)",
    size: "small",
    price: 24,
    sku: "SMA-0053",
    posName: "Small Merguez",
    posPrice: 24,
  },
  {
    name: "Ethiopian - Kitfo",
    size: "regular",
    price: 43,
    sku: "ETH-0020",
    posName: "Ethiopian - Kitfo",
    posPrice: 43,
  },
  {
    name: "Ethiopian - Kitfo",
    size: "small",
    price: 29,
    sku: "SMA-0054",
    posName: "Small Kitfo",
    posPrice: 29,
  },
  {
    name: "American - Legend Chicken",
    size: "regular",
    price: 43,
    sku: "AME-0021",
    posName: "American - Legend Chicken",
    posPrice: 43,
  },
  {
    name: "American - Legend Chicken",
    size: "small",
    price: 29,
    sku: "SMA-0055",
    posName: "Small Legend Chicken",
    posPrice: 29,
  },
  {
    name: "American - Pepperoni",
    size: "regular",
    price: 38,
    sku: "AME-0022",
    posName: "American - Pepperoni",
    posPrice: 38,
  },
  {
    name: "American - Pepperoni",
    size: "small",
    price: 25,
    sku: "SMA-0056",
    posName: "Small Pepperoni",
    posPrice: 25,
  },
  {
    name: "American - Hawaiian",
    size: "regular",
    price: 49,
    sku: "AME-0023",
    posName: "American - Hawaiian",
    posPrice: 49,
  },
  {
    name: "American - Hawaiian",
    size: "small",
    price: 35,
    sku: "SMA-0057",
    posName: "Small Hawaiian",
    posPrice: 35,
  },
  {
    name: "Margherita",
    size: "regular",
    price: 28,
    sku: "MAR-0001",
    posName: "Margherita",
    posPrice: 28,
  },
  {
    name: "Margherita",
    size: "small",
    price: 19,
    sku: "SMA-0035",
    posName: "Small Margherita",
    posPrice: 19,
  },
  {
    name: "Tonno (Tuna)",
    size: "regular",
    price: 43,
    sku: "TON-0003",
    posName: "Tonno (Tuna)",
    posPrice: 43,
  },
  {
    name: "Tonno (Tuna)",
    size: "small",
    price: 29,
    sku: "SMA-0037",
    posName: "Small Tonno (Tuna)",
    posPrice: 29,
  },
  {
    name: "Ortolana (Vegetarian)",
    size: "regular",
    price: 41,
    sku: "ORT-0002",
    posName: "Ortolana (Vegetarian)",
    posPrice: 41,
  },
  {
    name: "Ortolana (Vegetarian)",
    size: "small",
    price: 27,
    sku: "SMA-0036",
    posName: "Small Ortolana (Vegetarian)",
    posPrice: 27,
  },
  {
    name: "Quattro Formaggi (Four Cheese)",
    size: "regular",
    price: 44,
    sku: "QUA-0004",
    posName: "Quattro Formaggi (Four Cheese)",
    posPrice: 44,
  },
  {
    name: "Quattro Formaggi (Four Cheese)",
    size: "small",
    price: 30,
    sku: "SMA-0038",
    posName: "Small Quattro Formaggi (Four Cheese)",
    posPrice: 30,
  },
  {
    name: "Frutti Di Mare (Seafood Pizza)",
    size: "regular",
    price: 44,
    sku: "FRU-0005",
    posName: "Frutti Di Mare (Seafood Pizza)",
    posPrice: 44,
  },
  {
    name: "Frutti Di Mare (Seafood Pizza)",
    size: "small",
    price: 29,
    sku: "SMA-0039",
    posName: "Small Frutti Di Mare (Seafood Pizza)",
    posPrice: 29,
  },
  {
    name: "Diavola Piccante (Spicy Italian Beef Salami)",
    size: "regular",
    price: 46,
    sku: "DIA-0006",
    posName: "Diavola Piccante (Spicy Italian Beef Salami)",
    posPrice: 46,
  },
  {
    name: "Diavola Piccante (Spicy Italian Beef Salami)",
    size: "small",
    price: 31,
    sku: "SMA-0040",
    posName: "Small Diavola Piccante (Spicy Italian Beef Salami)",
    posPrice: 31,
  },
  {
    name: "Quattro Stagioni (Four Seasons)",
    size: "regular",
    price: 49,
    sku: "QUA-0007",
    posName: "Quattro Stagioni (Four Seasons)",
    posPrice: 49,
  },
  {
    name: "Quattro Stagioni (Four Seasons)",
    size: "small",
    price: 34,
    sku: "SMA-0096",
    posName: "Small Quattro Stagioni",
    posPrice: 46,
  },
  {
    name: "Mortadella (Beef Ham)",
    size: "regular",
    price: 49,
    sku: "MOR-0008",
    posName: "Mortadella (Beef Ham)",
    posPrice: 49,
  },
  {
    name: "Mortadella (Beef Ham)",
    size: "small",
    price: 34,
    sku: "SMA-0042",
    posName: "Small Mortadella (Beef Ham)",
    posPrice: 34,
  },
  {
    name: "Prosciutto e Funghi (Veal Ham & Mushroom)",
    size: "regular",
    price: 52,
    sku: "PRO-0009",
    posName: "Prosciutto e Funghi (Veal Ham & Mushroom)",
    posPrice: 52,
  },
  {
    name: "Prosciutto e Funghi (Veal Ham & Mushroom)",
    size: "small",
    price: 36,
    sku: "SMA-0043",
    posName: "Small Prosciutto e Funghi (Veal Ham & Mushroom)",
    posPrice: 36,
  },
  {
    name: "Bresaola (Beef Dry Ham)",
    size: "regular",
    price: 58,
    sku: "BRE-0010",
    posName: "Bresaola (Beef Dry Ham)",
    posPrice: 58,
  },
  {
    name: "Bresaola (Beef Dry Ham)",
    size: "small",
    price: 39,
    sku: "SMA-0044",
    posName: "Small Bresaola (Beef Dry Ham)",
    posPrice: 39,
  },
  {
    name: "Focaccia Mortadella",
    size: "regular",
    price: 48,
    sku: "FOC-0024",
    posName: "Focaccia Mortadella",
    posPrice: 48,
  },
  {
    name: "Focaccia Mortadella",
    size: "small",
    price: 35,
    sku: "FOC-0222",
    posName: "Focaccia Mortadella small",
    posPrice: 35,
  },
  {
    name: "Focaccia Veal Ham",
    size: "regular",
    price: 42,
    sku: "FOC-0025",
    posName: "Focaccia Veal Ham",
    posPrice: 42,
  },
  {
    name: "Focaccia Veal Ham",
    size: "small",
    price: 29,
    sku: "FOC-0224",
    posName: "Focaccia Veal Ham small",
    posPrice: 29,
  },
  {
    name: "Focaccia Bresaola",
    size: "regular",
    price: 46,
    sku: "FOC-0026",
    posName: "Focaccia Bresaola",
    posPrice: 46,
  },
  {
    name: "Focaccia Bresaola",
    size: "small",
    price: 32,
    sku: "FOC-0223",
    posName: "Focaccia Bresaola small",
    posPrice: 32,
  },
  {
    name: "Nutella Pizza",
    size: "regular",
    price: 19,
    sku: "NUT-0027",
    posName: "Nutella Pizza",
    posPrice: 19,
  },
  {
    name: "Nutella Pizza",
    size: "small",
    price: 13,
    sku: "SMA-0058",
    posName: "Small Nutella Pizza",
    posPrice: 13,
  },
  {
    name: "Lotus Pizza",
    size: "regular",
    price: 19,
    sku: "LOT-0028",
    posName: "Lotus Pizza",
    posPrice: 19,
  },
  {
    name: "Lotus Pizza",
    size: "small",
    price: 13,
    sku: "SMA-0059",
    posName: "Small Lotus Pizza",
    posPrice: 13,
  },
  {
    name: "Pistachio Pizza",
    size: "regular",
    price: 19,
    sku: "PIS-0029",
    posName: "Pistachio Pizza",
    posPrice: 19,
  },
  {
    name: "Pistachio Pizza",
    size: "small",
    price: 13,
    sku: "SMA-0060",
    posName: "Small Pistachio Pizza",
    posPrice: 13,
  },
  {
    name: "Coca-Cola",
    size: "regular",
    price: 4,
    sku: "COC-0030",
    posName: "Coca-Cola",
    posPrice: 4,
  },
  {
    name: "Coca-Cola Zero",
    size: "regular",
    price: 4,
    sku: "COC-0031",
    posName: "Coca-Cola Zero",
    posPrice: 4,
  },
  {
    name: "Fanta",
    size: "regular",
    price: 4,
    sku: "FAN-0032",
    posName: "Fanta",
    posPrice: 4,
  },
  {
    name: "Sprite",
    size: "regular",
    price: 4,
    sku: "SPR-0033",
    posName: "Sprite",
    posPrice: 4,
  },
  {
    name: "Water",
    size: "regular",
    price: 1,
    sku: "WAT-0120",
    posName: "Water",
    posPrice: 2,
  },
] as const;

const normalize = (value: string) => value.toLowerCase().replace(/\s+/g, " ").trim();

export function resolvePosSku(productName: string, basePriceAed: number | string): string | undefined {
  const price = Number(basePriceAed);
  const normalizedName = normalize(productName);
  const exact = POS_SKU_ENTRIES.find((entry) => normalize(entry.name) === normalizedName && entry.price === price);
  if (exact) return exact.sku;
  const sameName = POS_SKU_ENTRIES.filter((entry) => normalize(entry.name) === normalizedName);
  if (sameName.length === 0) return undefined;
  return sameName
    .slice()
    .sort((a, b) => Math.abs(a.price - price) - Math.abs(b.price - price) || a.price - b.price)[0]?.sku;
}
